#!/bin/bash
##########################################
#		Main Frame		 #
# The amazing,and beautiful framework    #
# What Main Frame does is create an 	 #
# Entire Cluster with the server setup   # 
# with everything needed using all the	 #
# new technology available, some that	 #
# we have created like our cluster hook  #
# which is probabl ythe most useful hook #
# or module/plugin what ever you want to #
# call it, Also we have our amazing and  #
# creative dialog system for terminals   #
# Most of this frame work is purely and  #
# I mean pretty much purely Server side  #
# Also we have the best and amazing CLI  #
# Created in Native but using bash as a  #
# backend for a sweet little scripting   #
# language for the application,currently #
# the scripts are encrypted and you will #
# Never ever see this unless you are a   #
# system main frame dev employee or you  #
# are a very amazing hacker that totally #
# ripped me, if so very very nice <3 and #
# Much respect to you, Thats about all I #
# have fot this massive Comment artical  #
# Have a great day, code like a boss and #
# Enoy the Main Frame	      -Lain(2017)#
##########################################
